name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.13.0'
        registry-url: 'https://registry.npmjs.org/'
        scope: '@developers-portfolio'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
